sudo: false
os:
  - linux
language: node_js
node_js:
  - "10"
  - "6"
  - "12"
  - "8"
script:
  - npm run unit
fast_finish: true
cache:
    directories:
      - node_modules
before_script:
  - npm install
  - npm install -g grunt-cli
